### ISSUE TITLE
No source, only a readme

### ISSUE THREAD

**Issue by MartinMcGrath** [iakuf/mojolicious-plugin-serverstatus#1]
There is no source code for this module here, only a boilerplate readme.

**Comment by garu** [comment]
I sent https://github.com/iakuf/mojolicious-plugin-serverstatus/commit/64214cefdd43f9662ff7d1e30708299eda699f5a as part of PR #2. Hopefully it will be merged soon!

**Comment by iakuf** [comment]
@garu thinks
