### ISSUE TITLE
Parallel::Scoreboard configuration not mentioned in docs

### ISSUE THREAD

**Issue by ravenhall** [iakuf/mojolicious-plugin-serverstatus#4]
Parallel::Scoreboard has a default log location of /var/run/server, which is not always accessible. This can be configured through Mojolicious::Plugin::ServerStatus by passing it through in the plugin configuration with the config key of scoreboard:

```
$self->plugin(
  'ServerStatus' => {
    path  => '/server-status',
    allow => ['127.0.0.1', '192.168.0.0/16'],
    scoreboard => "/some/other/dir"
  }
);
```

The documentation for this plugin should show how to configure this.

**Comment by iakuf** [comment]
Thanks
